[gedent]
default_extension = "inp"

[parameters]
zoraatoms = ["Ag"]
memory = 2000
basis_set = "ZORA old-ZORA-TZVPP def2-TZVPP/C"
charge = 0
dispersion = "D3bj"
level = "BP86"
mult = 1
nprocs = 16
solvation = true
start_hessian = false
solvent = "dichloromethane"
zora = true
maxiter = 256
