[gedent]
default_extension = "inp"

[parameters]
zoraatoms = ["Ag"]
memory = 2000
basis_set = ""
charge = 0
dispersion = ""
level = "r2scan-3c"
mult = 1
nprocs = 16
solvation = true
start_hessian = false
solvent = "dichloromethane"
zora = false
zora_basis = ""
maxiter = 256
