[[snippets]]
prefix = "beg"
scope = [ "latex" ]
body = """\\begin{$1}
  $0
\\end{$1}"""

[[snippets]]
prefix = "section"
scope = [ "latex" ]
body = '\\section{$1}'

[[snippets]]
prefix = "bold"
scope = [ "latex" ]
body = '\\textbf{$1}'

[[snippets]]
prefix = "italic"
scope = [ "latex" ]
body = '\\textit{$1}'

[[snippets]]
prefix = "quote"
scope = [ "latex" ]
body = """\'\'$1\`\`"""

[[snippets]]
prefix = "subsection"
scope = [ "latex" ]
body = '\\subsection{$1}'

[[snippets]]
prefix = "subsubsection"
scope = [ "latex" ]
body = '\\subsubsection{$1}'

[[snippets]]
prefix = "cite"
scope = [ "latex" ]
body = '\\cite{$1}'

[[snippets]]
prefix = "math"
scope = [ "latex" ]
body = '\$ $1 \$'

[[snippets]]
prefix = "chem"
scope = [ "latex" ]
body = '\\ce{$1}'

[[snippets]]
prefix = "subscript"
scope = [ "latex" ]
body = '\\textsubscript{$1}'

[[snippets]]
prefix = "upperscript"
scope = [ "latex" ]
body = '\\textsuperscript{$1}'

[[snippets]]
prefix = "enum"
scope = [ "latex" ]
body = """\\begin{enumerate}
  \\item $1
  \\item 
\\end{enumerate}"""

[[snippets]]
prefix = "itemize"
scope = [ "latex" ]
body = """\\begin{itemize}
  \\item $1
  \\item 
\\end{itemize}"""


[[snippets]]
prefix = "figure"
scope = [ "latex" ]
body = """\\begin{figure}[H]
	\\centering
	\\includegraphics[width=0.7\\linewidth]{./images/$1}
	\\caption{$2}
	\\label{fig:$3}
\\end{figure}
"""

[[snippets]]
prefix = "figure2"
scope = [ "latex" ]
body = """\\begin{figure}[H] % reminder to add \\usepackage{subcaption}
    \\centering
    \\begin{subfigure}{0.48\\linewidth}  % First subfigure
        \\centering
        \\includegraphics[width=1.0\\linewidth]{./images/}
        \\caption{Caption for Figure 1}
        \\label{fig:figure1}
    \\end{subfigure}
    \\hfill  % Add some horizontal space between the subfigures
    \\begin{subfigure}{0.48\\linewidth}  % Second subfigure
        \\centering
        \\includegraphics[width=1.0\\linewidth]{./images/}
        \\caption{Caption for Figure 2}
        \\label{fig:figure2}
    \\end{subfigure}
    \\caption{Overall caption for both subfigures}
    \\label{fig:subfigures}
\\end{figure}"""

[[snippets]]
prefix = "figure3"
scope = [ "latex" ]
body = """\\begin{figure}[H] % reminder to add \\usepackage{subcaption}
    \\centering
    \\begin{subfigure}[b]{0.30\\linewidth}  % First subfigure
        \\centering
        \\includegraphics[width=1.0\\linewidth]{./images/}
        \\caption{Caption for Figure 1}
        \\label{fig:figure1}
    \\end{subfigure}
    \\hfill  % Add some horizontal space between the subfigures
    \\begin{subfigure}[b]{0.30\\linewidth}  % Second subfigure
        \\centering
        \\includegraphics[width=1.0\\linewidth]{./images/}
        \\caption{Caption for Figure 2}
        \\label{fig:figure2}
    \\end{subfigure}
    \\hfill  % Add some horizontal space between the subfigures
    \\begin{subfigure}[b]{0.30\\linewidth}  % Second subfigure
        \\centering
        \\includegraphics[width=1.0\\linewidth]{./images/}
        \\caption{Caption for Figure 3}
        \\label{fig:figure3}
    \\end{subfigure}
    \\caption{Overall caption for the three subfigures}
    \\label{fig:subfigures}
\\end{figure}"""

[[snippets]]
prefix = "report"
scope = [ "latex" ]
body = """\\documentclass[a4paper, 11pt]{article}
\\usepackage[top=3cm, bottom=3cm, left = 2cm, right = 2cm]{geometry} 
\\geometry{a4paper} 
\\usepackage[utf8]{inputenc}
\\usepackage{subcaption}
\\usepackage{mhchem}
\\usepackage{siunitx}
\\usepackage{float}
\\usepackage{booktabs}
\\usepackage{textcomp}
\\usepackage{graphicx} 
\\usepackage{amsmath,amssymb}  
\\usepackage{bm}
\\usepackage[backend=biber,style=chem-acs]{biblatex}
\\usepackage[pdftex,bookmarks,colorlinks,breaklinks]{hyperref}  
\\hypersetup{linkcolor=black,citecolor=black,filecolor=black,urlcolor=black} % black links, for printed output
\\usepackage{memhfixc} 
\\usepackage{pdfsync}  
\\usepackage{fancyhdr}
\\pagestyle{fancy}

\\addbibresource{report.bib}

\\title{$1}
\\author{Vinicius C. Port}
\\date{\\today}

\\begin{document}
\\maketitle
\\tableofcontents

\\section{Introduction}

$2

\\section{Results}


\\printbibliography

\\end{document}
"""
