[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "fish" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = ["g", "e"]
run  = 'shell "helix $0" --block'
block = true
desc = "Open in helix"

[[mgr.prepend_keymap]]
on = "E"
for = "unix"
run = 'shell "helix $0" --block'
desc = "Edit in helix"

[[mgr.prepend_keymap]]
on = "@"
run = "seek 2000"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on  = "<C-n>"
run = "shell -- dragon -x -i -T %h"

# keymap.toml
[[mgr.prepend_keymap]]
on   = "<C-w>"
for  = "linux"
run  = "shell -- hyprctl hyprpaper reload ,%h"
desc = "Set hovered file as wallpaper"
