[accessibility]
ui_scale = 1.0500000081956387

[backdrop]
blur_intensity = 0.64999998547136784
enabled = true

[bar.default]
background_opacity = 0.669999985024333
center = [ "clock", "bar_2", "bar_3", "widget" ]
margin_edge = 1
margin_ends = 0
padding = 13
radius = 9
start = [
    "launcher",
    "wallpaper",
    "workspaces",
    "bar",
    "todo",
    "recorder",
    "screenshot",
    "keyboard_layout",
    "spacer_2",
    "bar_4"
]
thickness = 25

[calendar]
enabled = true
refresh_minutes = 30

    [calendar.account.personal_google]
    color = "primary"
    type = "google"

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.13999999687075615

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-widget-0000000000000001", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 128.0
    box_width = 810.0
    cx = 960.0
    cy = 958.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.41999999999999998
        background_radius = 15.0
        center_password_text = true
        input_opacity = 0.47000000000000003
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 956.0
    cy = 784.8599853515625
    output = "winit"
    placement_height = 1016.0
    placement_width = 1912.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 525.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 0.17000000000000001
        background_padding = 1
        background_radius = 7
        clock_style = "digital"

[plugin_settings."nightwatch75/todo"]
sound_on_complete = true

[plugin_settings."raycursive/github-prs"]
refresh_interval = 1203

[plugins]
enabled = [
    "blackbartblues/audio-switcher",
    "yuuto/calculator",
    "salemsayed/codexbar-meter",
    "raycursive/github-prs",
    "dunarand/tmux-provider",
    "nightwatch75/todo",
    "weinguyen/procmon",
    "tordex/nvtop",
    "noctalia/screen_recorder",
    "liamwh/emoji-picker",
    "noctalia/timer"
]

[shell]
corner_radius_scale = 0.40000000596046448
font_family = "Inter"

    [shell.animation]
    speed = 0.70000001043081284

    [shell.greeter_sync]
    auto_sync = true
    privilege_command = "ghostty -e pkexec"

    [shell.launcher]
    app_grid = true

    [shell.panel]
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 17

[theme]
builtin = "Nord"
community_palette = "Shien"
mode = "dark"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kitty", "niri", "qt", "starship" ]
    community_ids = [ "codex", "obsidian", "zed", "steam", "zathura", "bat", "fzf", "lazygit", "yazi" ]

[wallpaper]
directory = "/home/vport/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/vport/Pictures/wallpapers/nordic-wallpapers/wallpapers/earth-in-space.png"

    [wallpaper.last]
    path = "/home/vport/Pictures/wallpapers/nordic-wallpapers/wallpapers/earth-in-space.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/vport/Pictures/wallpapers/nordic-wallpapers/wallpapers/earth-in-space.png"

[widget.active_window]
enabled = false

[widget.bar]
type = "yuuto/calculator:bar"

[widget.bar_2]
type = "salemsayed/codexbar-meter:bar"

[widget.bar_3]
type = "raycursive/github-prs:bar"

[widget.bar_4]
type = "noctalia/timer:bar"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.spacer_2]
length = 214
type = "spacer"

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.widget]
scale = 1.1000000000000001
show_count = false
type = "weinguyen/procmon:widget"
